version: "3"

services:
  api:
    image: webb-tracker-api
    build: webb-tracker-api/.
  bot:
    image: webb-tracker-bot
    build: webb-tracker-bot/.
    depends_on:
      - api
    env_file:
      - token.env